#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Homebrew

export HOMEBREW_GITHUB_API_TOKEN=3789521a7271e8b4a66c42f6b74c42e908f17d0a

# Go - http://golang.org
export GOPATH=~/Documents/Code/go

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home

# Path
export PATH=/usr/local/bin:/usr/local/opt/openssl/bin:$PATH:$GOPATH/bin:/Users/dharper/bin:/Users/dharper/bin/maven/bin

# Use Sublime Text as editor
# export EDITOR='subl -w'
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"

function fig() {
  docker-compose "$@" 2> >(grep InsecurePlatform -v)
}

# ondir configuration
eval_ondir() {
  eval "`ondir \"$OLDPWD\" \"$PWD\"`"
}
chpwd_functions=( eval_ondir $chpwd_functions )
